lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_extractors:
        #        authorization_header:
        #            enabled: false
        #            name: Authorization
        #            prefix:
        cookie:
            enabled: true
            name:    Authorization
    set_cookies:
        # Full config with defaults:
        Authorization:
            lifetime: null
            samesite: none
            path: /
            domain: null
