<?php

namespace App\Infrastructure\Security\Symfony;

use App\Application\Service\PasswordEncoder;
use Faker\Provider\Base as BaseProvider;
use Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface;

class PasswordEncoderAdapter extends BaseProvider implements PasswordEncoder
{
    private $passwordEncoder;

    public function __construct(PasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    public function encode(string $password): string
    {
        //Since php 7, random salt is auto-generated by hash_password and is stored with password
        return $this->passwordEncoder->encodePassword($password, null);
    }
}
