api_login_check:
  path:
    en: /login_check
    de: /login_check

createUser:
    path:
      en: /user
      de: /benutzer
    controller: App\Infrastructure\Controller\RegisterUserController:handleRequest
    methods: [post]

createJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\CreateJobController:handleRequest
  methods: [post]

updateJob:
  path:
    en: /job
    de: /arbeit
  controller: App\Infrastructure\Controller\UpdateJobController:handleRequest
  methods: [put]

getJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\GetJobController:handleRequest
  methods: [get]
  requirements:
    uuid: \w{8}-\w{4}-\w{4}-\w{4}-\w{12}

deleteJob:
  path:
    en: /job/{uuid}
    de: /arbeit/{uuid}
  controller: App\Infrastructure\Controller\DeleteJobController:handleRequest
  methods: [delete]
  requirements:
    uuid: \w{8}-\w{4}-\w{4}-\w{4}-\w{12}
